---
title: "Guía 2 - Template para estadística descriptiva"
subtitle: "Laboratorio de datos 2023"
author: "Nombre Apellido"
format:
  html: 
    theme: cosmo
    fontsize: 1em
    linestretch: 1.15
editor: source
---

## Medidas de centralidad

- media: esta es mi definición de media con palabras. también lo puedo escribir en Latex:

$$ \text{media}(x) = \frac{1}{N} \sum_{i=1}^N  x_i$$

```{r}
library(tidyverse)
library(ggplot2)
library(gapminder)

# así es como lo puedo calcular en R
x <- c(3,4,2,5,6)
m1 <- mean(x)
# lo calculo de otra forma para comprobar
m2 <- sum(x)/length(x)
print(c(m1, m2))
```


- mediana: mi definición de mediana

En R:

```{r}
# así es como lo puedo calcular en R
x <- c(3,4,2,5,6)
print(median(x))
```

- moda: mi definición de moda
```{r}
#| eval: false
#| echo: true
#| warning: false

x <- c("mandarina", "mandarina", "pera", "pera", "pera", "tomate")
t <- table(x)
names(___) 
```


```{r}
# Crear el boxplot de diagrama de bigote
ggplot(data = gapminder, aes(x = continent, y = gdpPercap)) +
  geom_boxplot(outlier.shape = "diamond") +
  labs(title = "Boxplot de GDP per cápita por Continente",
       x = "Continente",
       y = "PIB per cápita ($)") +
  theme_minimal()

```

